forum/urls.py
import os.path

from django.conf.urls import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.views.generic.simple import direct_to_template
from my_forum.views import *

admin.autodiscover()

urlpatterns = patterns('',
    # Browsing
    (r'^$',main_page),
    (r'^add/thread/$',save_thread),
    (r'^thread/(?P<thread_slug>[-\w]+)/$', save_post),
    (r'^post/edit/(?P<thread_slug>[-\w]+)/$', save_post),
    
    # Session management
    (r'^login/$','django.contrib.auth.views.login'),
    (r'^logout/$', logout_page),
    (r'^register/$', register_page),
    (r'^register/success/$',direct_to_template,
     {'template': 'registration/register_success.html'}
     ),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         { 'document_root' : settings.STATIC_ROOT}),         
    #media
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    
    
     
    #registratin : (uses the default backed from registration app)
    #                some changes are made, we use a customised form to take into consideration additional infos
    #                urls from spec_registration, to use the new form_class
    #cities       
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),  
)

my_forum/forms.py
'''
Created on 14 nov. 2012

@author: naamane.othmane
'''

from django.contrib.auth.models import User
from django import forms
from django.utils.translation import ugettext_lazy as _
from my_forum.models import Thread,Post
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout,  Submit, HTML
from crispy_forms.bootstrap import  FormActions
from django.template.defaultfilters import slugify




# I put this on all required fields, because it's easier to pick up
# on them with CSS or JavaScript if they have a class of "required"
# in the HTML. Your mileage may vary. If/when Django ticket #3515
# lands in trunk, this will no longer be necessary.
attrs_dict = {'class': 'required'}






class RegistrationForm(forms.Form):
    """
    """    
    last_name = forms.RegexField(regex=r'^[a-zA-Z]+$',
                                max_length=20,
                                widget=forms.TextInput(attrs=attrs_dict),
                                label=_("Last name"),
                                error_messages={'invalid': _(u"Only caracters are accepted.")})
    first_name = forms.RegexField(regex=r'^[a-zA-Z]+$',
                                max_length=20,
                                widget=forms.TextInput(attrs=attrs_dict),
                                label=_("First name"),
                                error_messages={'invalid': _(u"Only caracters are accepted.")})
    username = forms.RegexField(regex=r'^[a-zA-Z]+$',
                                max_length=30,
                                widget=forms.TextInput(attrs=attrs_dict),
                                label=_("Username"),
                                error_messages={'invalid': _(u"Only caracters are accepted.")})
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                                                               maxlength=75)),
                             label=_("E-mail"))
    password = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
                                min_length = 8,
                                error_messages={'invalid': _(u"Minimum 8 caracters.")},
                                label=_("Password"))
    tos = forms.BooleanField(widget=forms.CheckboxInput(attrs=attrs_dict),
                             label=_(u"I agree to the Forum Terms of Service and Privacy Policy."),
                             error_messages={ 'required': _(u"You must accept Forum's Terms of Service and Privacy Policy")})
        
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'id_registration'        
        self.helper.form_method = 'post'
        self.helper.form_action = '.'
        self.helper.form_class = "form-horizontal"
        self.helper.error_text_inline = True
        self.helper.layout = Layout(                                                       
            'username',
            'password',
            'email',
            'last_name',
            'first_name',
            'tos',
            FormActions(
                Submit('submit', 'Send', css_class="btn-primary"),
                HTML('<a class="btn" href="/">Cancel</a>')         
                )
            )
        super(RegistrationForm, self).__init__(*args, **kwargs)
        
    def clean_email(self):
        """
        Validate that the supplied email address is unique for the
        site.
        
        """
        if User.objects.filter(email__iexact=self.cleaned_data['email']):
            raise forms.ValidationError(_("This email address is already in use. Please supply a different email address."))
        return self.cleaned_data['email']
    
    def clean_username(self):
        """
        Validate that the username is alphanumeric and is not already
        in use.
        
        """
        existing = User.objects.filter(username__iexact=self.cleaned_data['username'])
        if existing.exists():
            raise forms.ValidationError(_("A user with that username already exists."))
        else:
            return self.cleaned_data['username']

class ThreadForm(forms.Form):
    thread_title = forms.CharField(max_length=40,
                                widget=forms.TextInput(attrs=attrs_dict),
                                label=_("Thread title"))
    post_title = forms.CharField(max_length=40,
                                widget=forms.TextInput(attrs=attrs_dict),
                                label=_("Post Title"))
    post_description =  forms.CharField(max_length=4000,
                                widget=forms.Textarea(attrs=attrs_dict),
                                label=_("Description"))
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = 'id_new_thread'        
        self.helper.form_method = 'post'
        self.helper.form_action = '.'
        self.helper.form_class = "form-horizontal"
        self.helper.error_text_inline = True
        self.helper.layout = Layout(                                                       
            'thread_title',
            'post_title',
            'post_description',
            FormActions(
                Submit('submit', 'Send', css_class="btn-primary"),
                HTML('<a class="btn" href="/">Cancel</a>')         
                )
            )
        super(ThreadForm, self).__init__(*args, **kwargs)
        
    def clean_thread_title(self):
        """
        Validate that the username is alphanumeric and is not already
        in use.
        """
        existing = Thread.objects.filter(slug__iexact=slugify(self.cleaned_data['thread_title']))
        if existing.exists():
            raise forms.ValidationError(_("Thread already exist."))
        else:
            return self.cleaned_data['thread_title']


class PostForm(forms.Form):
    post_id = forms.CharField(widget=forms.HiddenInput(attrs={'value':'2'}))
    thread_nom = forms.CharField(widget=forms.HiddenInput(attrs={'value':'2'}))
    post_description =  forms.CharField(max_length=4000,
                                widget=forms.Textarea(attrs=attrs_dict),
                                label=_("Post"))
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_id = ''        
        self.helper.form_method = 'post'
        self.helper.form_action = '.'
        self.helper.form_class = "form-inline"
        self.helper.error_text_inline = True
        self.helper.layout = Layout('post_description','post_id','thread_nom',
                                    FormActions(
                                                Submit("btn-add-post", "Add Post", css_class="btn-primary")
                )
            )
        super(PostForm, self).__init__(*args, **kwargs)

forum/templates/brows_thread.html
{% extends "general.html" %}
{% block head_title %}Forum - {{thread.title}}{% endblock %}

{% block site_wrapper %}	
	
	<div class="row-fluid">
		<div class="span12">
			{% include "posts_list.html" %}
		</div>
		{% include "post_form.html" %}
		
	</div>
	
{% endblock %}
{% block extra_content %}
	<script type="text/javascript">
		$('.edit_post').bind('click', function() {
  			var link = $(this).attr("href");
  			var td_elm = $(this).parent();
  			td_elm.load(link,null,function(){
				$("#submit-id-btn-edit-post").submit(post_save);
  			});
  			return false;
		});
		
		
		function post_save(){
			  var item = $(this).parent().parent();
			  var data = {
			    post_id: item.find("#post_id").val(),
				post_description: item.find("#id_post_description").val(),
				csrfmiddlewaretoken: getCookie('csrftoken')
			  };
			  $.post("/thread/" + $('#id_thread_nom').val() +"/?ajax",data,function(result){
			    if (result!='failure') {
				  $('.span12').childre().remove();
				  $('.span12').html(result);
				 $('.edit_post').bind('click', function() {
					var link = $(this).attr("href");
					var td_elm = $(this).parent();
					td_elm.load(link,null,function(){
						$("#submit-id-btn-edit-post").submit(post_save);
						});
					return false;
				});
				}
				else{
				  alert("Failed before saving.")
				}
			  }
			  );
			  return false;
	}
	</script>
{% endblock%}

forum/templates/general.html
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="{{ LANGUAGE_CODE }}"> <!--<![endif]-->
<head>	
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">	
	
	<link rel="stylesheet" href="{{ MEDIA_URL }}css/libs/bootstrap.min.css">
	<link rel="stylesheet" href="{{ MEDIA_URL }}css/libs/bootstrap-responsive.min.css">		
	<style>
      
    </style>				
	<script>window.jQuery || document.write('<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"><\/script>')</script>
	<script src="{{ MEDIA_URL }}js/libs/bootstrap/bootstrap.min.js"></script>	
	<link rel="shortcut icon" href="{{ MEDIA_URL }}images/favicon.ico" type="image/x-icon" />	
	{% block extra_head %}{% endblock %}

	<title>
		{% block title %} 
			{{ SITE_NAME }}|
		{% endblock %}
		{% block head_title %}
		{%endblock%}
	</title>	
	<!-- google analytics -->
</head>

<body>
	<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->
	
	<div class="container" style="padding-top: 10px">
		<div class="navbar">
	    <div class="navbar-inner">
	      <div class="container">
	        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </a>
	        <a class="brand" href="/">Forum</a>
	         {% if user.is_authenticated %}
		        <div class="btn-group pull-right">
					<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
						  <i class="icon-user"></i> {{ user.username }}
						  <span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
					  <li><a href="/logout/">Sign Out</a></li>
					</ul>
				</div>
	         {% else %}
	         <ul class="nav pull-right">
	        	<a class="btn" href="/login/">Login</a>
	            <a class="btn" href="/register/">Register</a>
	         </ul>
	         {% endif %}
	      </div>
	    </div><!-- /navbar-inner -->
	</div>
		{% block site_wrapper %}{% endblock %}
		<hr>
		<footer>
        	<p>&copy; myForum 2012</p>
    	</footer>
	</div>
	
	
	{% block extra_content %}{% endblock %}
	
	
</body>
</html>

forum/templates/index.html
{% extends "general.html" %}
{% block head_title %}Forum{% endblock %}

{% block site_wrapper %}	
	
	<form class="well form-search">
  		<input type="text" class="input-medium search-query">
  		<button type="submit" class="btn">Search</button>
  		<a href="/add/thread/" class="btn btn-primary">New thread</a>
	</form>
	<div class="row-fluid">
		<div class="span12">
			{% if threads %}
				<table class="table table-bordered table-striped" id="t_threads_list">
					<thead>
						<tr>
							<th>Thread / Title</th>
							<th>Last Post By</th>
							<th>Replies</th>
						</tr>
					</thead>
					<tbody>
						{% for thread in threads %}
							<tr>
								<td><a href="/thread/{{ thread.slug }}">{{ thread.title }}</a></td>
								<td>{{ thread.last_post_user.username }}</td>
								<td>{{ thread.replies }}</td>
							</tr>
						{% endfor %}
					</tbody>
					
				</table>
			{% else %}
				<p><h3>No Tread found.</h3></p>
			{% endif %}
			
		</div>
	</div>
	
{% endblock %}

forum/templates/post_form.html
{% load crispy_forms_tags %}
<div class="span6">
{% if form.errors %}
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert" href="#">×</a>
            <p><strong>Oh snap!</strong> Check errors.</p>
        </div>
    	{% endif %}		        
{% crispy form form.helper %}	

</div>

forum/templates/posts_list.html
	<h2>{{thread.title}}</h2>
	<br>
	{% for post in posts %}
		<table class="table table-striped table-bordered table-condensed">
			<thead>
				<tr>
					<th colspan="2">{{  post.created_at }}</th>
				</tr>
			</thead>
			<tbody>
					<tr>
						<td width="20%"><h4>{{ post.created_by.username }}</h4></td>
						<td>
							<p>{{ post.description }}</p> <br>
							{% if not forloop.first %}
							 	{% if post.created_by.username == user.username %}
							 		<a href="/post/edit/{{thread.slug}}/?post_id={{post.id}}" class="edit_post">Edit</a> | <a href="" class="delete">Delete</a>
							 	{% endif %}
							{% endif %}
						</td> 
					</tr>
			</tbody>
		</table>
	{% endfor %}
	

forum/templates/thread_save.html
{% extends "general.html" %}
{% load crispy_forms_tags %}
{% block head_title %}New Thread{% endblock %}

{% block site_wrapper %}	
	
	
	<div class="row-fluid">
		<div class="span8">
				<h2>New Thread:</h2><br>
				{% if form.errors %}
	            <div class="alert alert-error">
	                <a class="close" data-dismiss="alert" href="#">×</a>
	                <p><strong>Oh snap!</strong> Check errors.</p>
	            </div>
	        	{% endif %}		        
	            {% crispy form form.helper %}		    
		</div>	
	</div>
	
{% endblock %}